/*
 * File: examples-projects/xc8/debug/debug_display_i2c.X/project_config.h
 */

#ifndef EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_I2C_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_I2C_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 8000000UL
#define DRV_DEBUG_BACKEND_UART 0
#define DRV_DEBUG_BACKEND_DISPLAY 1
#define DRV_DEBUG_BACKEND_PINS 0
#define DRV_DEBUG_DISPLAY_TYPE_LCD_2X16 1
#define DRV_DEBUG_DISPLAY_INTERFACE_I2C 1
#define DRV_DEBUG_DISPLAY_INTERFACE_PARALLEL 0
#define DRV_DEBUG_DISPLAY_I2C_ADDR 0x27u

#include "../../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_I2C_PROJECT_CONFIG_H */
