#ifndef EXAMPLES_PROJECTS_XC8_ACTUATOR_POSITION_DRIVE_ADC_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_ACTUATOR_POSITION_DRIVE_ADC_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 10000000UL
#include "../../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_ACTUATOR_POSITION_DRIVE_ADC_PROJECT_CONFIG_H */
