/*
 * File: examples-projects/xc8/debug_multi_backend.X/project_config.h
 */

#ifndef EXAMPLES_PROJECTS_XC8_DEBUG_MULTI_BACKEND_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_DEBUG_MULTI_BACKEND_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 8000000UL
#define DRV_DEBUG_BACKEND_DISPLAY 1
#define DRV_DEBUG_DISPLAY_TYPE_LCD_2X16 1
#define DRV_DEBUG_DISPLAY_INTERFACE_I2C 1
#define DRV_DEBUG_DISPLAY_I2C_ADDR 0x27u
#define DRV_DEBUG_BACKEND_PINS 1
#define DRV_DEBUG_PINS_INTERFACE_GPIO 1
#define DRV_DEBUG_PINS_PORT PORTC
#define DRV_DEBUG_PINS_TRIS TRISC
#define DRV_DEBUG_PINS_START_BIT 0u
#define DRV_DEBUG_PINS_CHANNEL_COUNT 4u

#include "../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_DEBUG_MULTI_BACKEND_PROJECT_CONFIG_H */
