#ifndef EXAMPLES_PROJECTS_XC8_AC_PHASE_CONTROL_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_AC_PHASE_CONTROL_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 10000000UL

#ifndef AC_PHASE_CONTROL_DIAGNOSTIC
#define AC_PHASE_CONTROL_DIAGNOSTIC 0
#endif

#ifndef AC_PHASE_CONTROL_SELECTED_TIMER
#define AC_PHASE_CONTROL_SELECTED_TIMER AC_PHASE_CONTROL_TIMER2
#endif

#include "../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_AC_PHASE_CONTROL_PROJECT_CONFIG_H */
