/*
 * File: examples-projects/xc8/debug/debug_pins_gpio.X/project_config.h
 */

#ifndef EXAMPLES_PROJECTS_XC8_DEBUG_PINS_GPIO_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_DEBUG_PINS_GPIO_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 8000000UL
#define DRV_DEBUG_BACKEND_UART 0
#define DRV_DEBUG_BACKEND_DISPLAY 0
#define DRV_DEBUG_BACKEND_PINS 1
#define DRV_DEBUG_PINS_INTERFACE_GPIO 1
#define DRV_DEBUG_PINS_INTERFACE_I2C 0
#define DRV_DEBUG_PINS_PORT PORTC
#define DRV_DEBUG_PINS_TRIS TRISC
#define DRV_DEBUG_PINS_START_BIT 0u
#define DRV_DEBUG_PINS_CHANNEL_COUNT 4u
#define DRV_DEBUG_PINS_PULSE_US 10000UL

#include "../../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_DEBUG_PINS_GPIO_PROJECT_CONFIG_H */
