/*
 * File: examples-projects/xc8/debug/debug_display_parallel.X/project_config.h
 */

#ifndef EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_PARALLEL_PROJECT_CONFIG_H
#define EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_PARALLEL_PROJECT_CONFIG_H

#define PIC_PLATFORM_CLOCK_HZ 8000000UL
#define DRV_DEBUG_BACKEND_UART 0
#define DRV_DEBUG_BACKEND_DISPLAY 1
#define DRV_DEBUG_DISPLAY_TYPE_LCD_2X16 1
#define DRV_DEBUG_DISPLAY_INTERFACE_PARALLEL 1

#include "../../../../core/config/project_config_template.h"

#endif /* EXAMPLES_PROJECTS_XC8_DEBUG_DISPLAY_PARALLEL_PROJECT_CONFIG_H */
